In [36]:
#numericalpy: scientific & mathematical ops & n-d arrays
import numpy as np
a= np.array([1,2,3])
print(a);

[1 2 3]


In [37]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [38]:
#ndim: used for finding dimensions of array
print(a.ndim)

1


In [39]:
print(b.ndim)

2


In [40]:
#item: memory occupied by each element in a array (in bytes) OR bytesize
print(a.itemsize)

8


In [41]:
print(b.itemsize)

8


In [42]:
#dtype: to find the datatype of the element of the array
print(a.dtype)

int64


In [43]:
print(b.dtype)

int64


In [44]:
#size: no of elements in the array & shape: no of rows and no column (r,c)
print(b.size)
print(b.shape)

6
(2, 3)


In [45]:
#reshape: change the r & c of the array
w= b.reshape(3,2)
print(w)

[[1 2]
 [3 4]
 [5 6]]


In [46]:
#linspace: used to return evenly spaced nums in given range (1-d array), cretes dummy data on req
d= np.linspace(1,100,10)
print(d)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [47]:
print("Max", d.max())
print("Min", d.min())
print("Sum", d.sum())

Max 100.0
Min 1.0
Sum 505.0


In [48]:
#pandas:Data Analysis Library developed on the top of numpy & contains 2 types of data structures -1. Series & 2. Dataframe
#Series: class in pandas used for storing 1-d array & Dataframes- stores 2-d array