In [35]:
#ASSIGNMENT_1
import numpy as np
import pandas as pd

In [36]:
# Create a 1D NumPy array of numbers from 0 to 9.
arr1 = np.arange(0,10,1)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [37]:
#Create a 3x3 NumPy array filled with all zeros.
arr2 =np.array([[0,0,0],[0,0,0],[0,0,0]])
print(arr2)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [38]:
#Create a 3x3 identity matrix.
arr3 =np.array([[1,0,0],[0,1,0],[0,0,1]])
print(arr3)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [39]:
#Generate an array of 10 random numbers between 0 and 1.
arr4 = np.linspace(0,1,10)
print(arr4)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [40]:
#Reshape a 1D array of size 9 into a 3x3 matrix.
arr5 = np.arange(11,20,1)
#arr5.size
arr5= arr5.reshape(3,3)
print(arr5)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [83]:
#Compute the dot product of two matrices.
pdt = np.dot(arr3,arr5)
print(pdt)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [84]:
#Create a Pandas Series from a list.
sr1 = pd.Series([1,2,3,4,5])
print(sr1)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [85]:
#Create a DataFrame from a dictionary.
dt={
    "EmpId" : [101,102,103,104,105],
    "Age" : [29,36,32,45,50],
    "City" :["Bareilly","Kanpur",None,"Lucknow","Agra"],
}
df1 =pd.DataFrame(dt)
df1

EmpId  Age      City
0    101   29  Bareilly
1    102   36    Kanpur
2    103   32      None
3    104   45   Lucknow
4    105   50      Agra

In [86]:
#Check for missing values in a DataFrame.
df1.isnull().sum()

EmpId    0
Age      0
City     1
dtype: int64

In [87]:
#Drop the 'City' column from the DataFrame.
df1.drop("City",axis="columns")

EmpId  Age
0    101   29
1    102   36
2    103   32
3    104   45
4    105   50